name: OCPI Publish

on:
    push:
        tags:
            - "R-*"

permissions:
    contents: read

jobs:
    build:

        concurrency: ocpi-publish

        runs-on: ubuntu-latest

        steps:
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Checkout IZIVIA OCPI toolkit library code from GH
                uses: actions/checkout@v3

            -   name: Create a GH release
                env:
                    VERSION: ${{ github.ref_name }}
                run: |-
                    echo "RELEASE_NAME=Version ${VERSION#R-}" >> $GITHUB_ENV
                    echo $GITHUB_ENV
                    gh release create ${{ github.ref }} --generate-notes --title ${RELEASE_NAME}
